# -*- coding: utf-8 -*-
"""2. Ще трохи математики

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ppc-ntu-khpi/34-2024-python-0-Python-Exercises/blob/main/2_%D0%A9%D0%B5_%D1%82%D1%80%D0%BE%D1%85%D0%B8_%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B8.ipynb

# Ще трохи математики

1. Обчисліть радіус кола, знаючи його площу. Нагадаємо формулу:
$$
  S=\pi*R^2 => R =\sqrt{\frac{S}{\pi}}
$$
Для обчислення скористаємось знайомими функціями ```sqrt``` та ```pi``` з пакету ```math```.
"""

from math import sqrt,pi
S = float(input('Введіть площу кола: '))
r = sqrt(S/pi)
print ('Радіус дорівнює %6.3f см' %r)

"""2. А тепер за зразком знайдіть в наступній комірці площу сфери та об'єм кулі. Нагадуємо формули:
$$
  S=4*\pi*R^2    
$$
$$
  V=\frac{4}{3}*\pi*R^3
$$
Також нагадаємо, що ступінь в Python задається так: ```**```
"""

import math

def surface_area_of_sphere(radius):
    # Формула для площі поверхні сфери: S = 4 * π * R^2
    return 4 * math.pi * radius ** 2

def volume_of_sphere(radius):
    # Формула для об'єму сфери: V = (4/3) * π * R^3
    return (4/3) * math.pi * radius ** 3

print(f"Площа поверхні сфери з радіусом {R}: {surface_area:.1f}")
print(f"Об'єм сфери з радіусом {R}: {volume:.1f}")

"""3. А ще давайте переведемо температуру за Фаренгейтом у градуси Цельсія і навпаки. Формули тут надзвичайно прості:
$$
  C=(F-32)*0.5556
$$
$$
  F=C*1.8+32
$$
Спробуйте в наступній комірці! Пам'ятайте про "красиве" введення і виведення даних.
"""

def fahrenheit_to_celsius(fahrenheit):
    # Формула для перетворення з Фаренгейта в Цельсій: C = (F - 32) * 0.5556
    return (fahrenheit - 32) * 0.5556

def celsius_to_fahrenheit(celsius):
    # Формула для перетворення з Цельсія в Фаренгейт: F = C * 1.8 + 32
    return celsius * 1.8 + 32

F = 100  # Температура в Фаренгейтах
C = 36.6  # Температура в Цельсіях

# Виведення результатів
print(f"{F}°F = {celsius:.1f}°C")
print(f"{C}°C = {fahrenheit:.1f}°F")

"""Ще більше простих вправ з Python - [тут](https://www.w3resource.com/python-exercises/python-basic-exercises.php)"""